### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by sarataylor1255** [mediadown/Onlyfans-Downloader#1]
I also bought the premium edition. When I run it for model media scraping, it downloads a 1 or 2 kb rar file with nothing inside.

**Comment by mediadown** [comment]
Dear mediadown/Onlyfans-Downloader,
   Thank you for your support. We would like to inform you that Onlyfans
has updated these days and cause some bug.    We are pleased to inform you
that our team has identified and fixed the problem. But the chrome store
don't accept  the update now, if you need to use it sooner, you will need
to reinstall it manually using the link provided:
https://hlsdownloader.com/how-to-install-onlyfans-downloader-from-a-zip-file/
    If it still doesn't work please give me the creator's name I will help
you out.

Best regards,
Roger

**Comment by sarataylor1255** [comment]
bro! i have installed it. It doesn't download the videos when u try, but only downloads a zip file of 2–3 kbs

**Comment by sarataylor1255** [comment]
![Uploading aa.png…]()

**Comment by mediadown** [comment]
Bro, the image is not upload.Send the creator's name to
***@***.***, I will help you out.

**Comment by sarataylor1255** [comment]
send u the creator name to where?

**Comment by sarataylor1255** [comment]
@xactorfab (OF model)

**Comment by sarataylor1255** [comment]
DRM videos doent downloading from purchase

**Comment by mediadown** [comment]
> from

it's working now. If you want to down drm please download desktop version in https://hlsdownloader.com

Thank you.

**Comment by foglmagna** [comment]
Hello,
I have a problem. When I open OnlyFans, there is no download link next to the image or video.....I don't want to download whole profiles, only individual images. Is it possible to do this?
Thank you in advance.

**Comment by mediadown** [comment]
Hi:
    Thank you for your email. You can choose the time period to download
the videos.
    You can follow this tutorial:
https://hlsdownloader.com/how-to-down-onlyfans-images-videos-from-a-specific-date/

Best regards
Roger
